# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aNjAf2xBArj_7RqOXTmZip0III4pBenF
"""

import pandas as pd

df = pd.read_csv("Salary_Data.csv")
df

import numpy as np
X = np.array(df['YearsExperience']).reshape(-1, 1)
y = np.array(df['Salary']).reshape(-1, 1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.9, random_state=42)

from sklearn.linear_model import LinearRegression

regr = LinearRegression()

regr.fit(X_train, y_train)
print(regr.score(X_test, y_test))

y_pred = regr.predict(np.array(1.7).reshape(-1,1))
y_pred[0][0]

import pickle
filename = 'finalized_model.pkl'
pickle.dump(regr, open(filename, 'wb'))

loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
result

